// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeepAliveMsg.proto

package com.fc.common.socket.msg;

public final class KeepAliveMsg {
  private KeepAliveMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.C2S)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户端发包时的格林威治时间戳，单位毫秒
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code tutorial.C2S}
   */
  public  static final class C2S extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.C2S)
      C2SOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S.newBuilder() to construct.
    private C2S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2S_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fc.common.socket.msg.KeepAliveMsg.C2S.class, com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     *客户端发包时的格林威治时间戳，单位毫秒
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fc.common.socket.msg.KeepAliveMsg.C2S)) {
        return super.equals(obj);
      }
      com.fc.common.socket.msg.KeepAliveMsg.C2S other = (com.fc.common.socket.msg.KeepAliveMsg.C2S) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fc.common.socket.msg.KeepAliveMsg.C2S prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.C2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.C2S)
        com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2S_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fc.common.socket.msg.KeepAliveMsg.C2S.class, com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder.class);
      }

      // Construct using com.fc.common.socket.msg.KeepAliveMsg.C2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2S_descriptor;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2S getDefaultInstanceForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.C2S.getDefaultInstance();
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2S build() {
        com.fc.common.socket.msg.KeepAliveMsg.C2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2S buildPartial() {
        com.fc.common.socket.msg.KeepAliveMsg.C2S result = new com.fc.common.socket.msg.KeepAliveMsg.C2S(this);
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fc.common.socket.msg.KeepAliveMsg.C2S) {
          return mergeFrom((com.fc.common.socket.msg.KeepAliveMsg.C2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fc.common.socket.msg.KeepAliveMsg.C2S other) {
        if (other == com.fc.common.socket.msg.KeepAliveMsg.C2S.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fc.common.socket.msg.KeepAliveMsg.C2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fc.common.socket.msg.KeepAliveMsg.C2S) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *客户端发包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *客户端发包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端发包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.C2S)
    }

    // @@protoc_insertion_point(class_scope:tutorial.C2S)
    private static final com.fc.common.socket.msg.KeepAliveMsg.C2S DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fc.common.socket.msg.KeepAliveMsg.C2S();
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.C2S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2S>
        PARSER = new com.google.protobuf.AbstractParser<C2S>() {
      @java.lang.Override
      public C2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fc.common.socket.msg.KeepAliveMsg.C2S getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器回包时的格林威治时间戳，单位毫秒
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code tutorial.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2C_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fc.common.socket.msg.KeepAliveMsg.S2C.class, com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     *服务器回包时的格林威治时间戳，单位毫秒
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fc.common.socket.msg.KeepAliveMsg.S2C)) {
        return super.equals(obj);
      }
      com.fc.common.socket.msg.KeepAliveMsg.S2C other = (com.fc.common.socket.msg.KeepAliveMsg.S2C) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fc.common.socket.msg.KeepAliveMsg.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.S2C)
        com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fc.common.socket.msg.KeepAliveMsg.S2C.class, com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder.class);
      }

      // Construct using com.fc.common.socket.msg.KeepAliveMsg.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2C_descriptor;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2C getDefaultInstanceForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.S2C.getDefaultInstance();
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2C build() {
        com.fc.common.socket.msg.KeepAliveMsg.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2C buildPartial() {
        com.fc.common.socket.msg.KeepAliveMsg.S2C result = new com.fc.common.socket.msg.KeepAliveMsg.S2C(this);
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fc.common.socket.msg.KeepAliveMsg.S2C) {
          return mergeFrom((com.fc.common.socket.msg.KeepAliveMsg.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fc.common.socket.msg.KeepAliveMsg.S2C other) {
        if (other == com.fc.common.socket.msg.KeepAliveMsg.S2C.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fc.common.socket.msg.KeepAliveMsg.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fc.common.socket.msg.KeepAliveMsg.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *服务器回包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *服务器回包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器回包时的格林威治时间戳，单位毫秒
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.S2C)
    }

    // @@protoc_insertion_point(class_scope:tutorial.S2C)
    private static final com.fc.common.socket.msg.KeepAliveMsg.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fc.common.socket.msg.KeepAliveMsg.S2C();
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @java.lang.Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fc.common.socket.msg.KeepAliveMsg.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2SMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.C2SMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    boolean hasC2S();
    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    com.fc.common.socket.msg.KeepAliveMsg.C2S getC2S();
    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder getC2SOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.C2SMsg}
   */
  public  static final class C2SMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.C2SMsg)
      C2SMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2SMsg.newBuilder() to construct.
    private C2SMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2SMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2SMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2SMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder subBuilder = null;
              if (c2S_ != null) {
                subBuilder = c2S_.toBuilder();
              }
              c2S_ = input.readMessage(com.fc.common.socket.msg.KeepAliveMsg.C2S.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(c2S_);
                c2S_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2SMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2SMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.class, com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.Builder.class);
    }

    public static final int C2S_FIELD_NUMBER = 1;
    private com.fc.common.socket.msg.KeepAliveMsg.C2S c2S_;
    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    public boolean hasC2S() {
      return c2S_ != null;
    }
    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    public com.fc.common.socket.msg.KeepAliveMsg.C2S getC2S() {
      return c2S_ == null ? com.fc.common.socket.msg.KeepAliveMsg.C2S.getDefaultInstance() : c2S_;
    }
    /**
     * <code>.tutorial.C2S c2s = 1;</code>
     */
    public com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder getC2SOrBuilder() {
      return getC2S();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (c2S_ != null) {
        output.writeMessage(1, getC2S());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (c2S_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getC2S());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fc.common.socket.msg.KeepAliveMsg.C2SMsg)) {
        return super.equals(obj);
      }
      com.fc.common.socket.msg.KeepAliveMsg.C2SMsg other = (com.fc.common.socket.msg.KeepAliveMsg.C2SMsg) obj;

      if (hasC2S() != other.hasC2S()) return false;
      if (hasC2S()) {
        if (!getC2S()
            .equals(other.getC2S())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasC2S()) {
        hash = (37 * hash) + C2S_FIELD_NUMBER;
        hash = (53 * hash) + getC2S().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fc.common.socket.msg.KeepAliveMsg.C2SMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.C2SMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.C2SMsg)
        com.fc.common.socket.msg.KeepAliveMsg.C2SMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2SMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2SMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.class, com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.Builder.class);
      }

      // Construct using com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (c2SBuilder_ == null) {
          c2S_ = null;
        } else {
          c2S_ = null;
          c2SBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_C2SMsg_descriptor;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2SMsg getDefaultInstanceForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2SMsg build() {
        com.fc.common.socket.msg.KeepAliveMsg.C2SMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.C2SMsg buildPartial() {
        com.fc.common.socket.msg.KeepAliveMsg.C2SMsg result = new com.fc.common.socket.msg.KeepAliveMsg.C2SMsg(this);
        if (c2SBuilder_ == null) {
          result.c2S_ = c2S_;
        } else {
          result.c2S_ = c2SBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fc.common.socket.msg.KeepAliveMsg.C2SMsg) {
          return mergeFrom((com.fc.common.socket.msg.KeepAliveMsg.C2SMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fc.common.socket.msg.KeepAliveMsg.C2SMsg other) {
        if (other == com.fc.common.socket.msg.KeepAliveMsg.C2SMsg.getDefaultInstance()) return this;
        if (other.hasC2S()) {
          mergeC2S(other.getC2S());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fc.common.socket.msg.KeepAliveMsg.C2SMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fc.common.socket.msg.KeepAliveMsg.C2SMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fc.common.socket.msg.KeepAliveMsg.C2S c2S_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fc.common.socket.msg.KeepAliveMsg.C2S, com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder, com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder> c2SBuilder_;
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public boolean hasC2S() {
        return c2SBuilder_ != null || c2S_ != null;
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.C2S getC2S() {
        if (c2SBuilder_ == null) {
          return c2S_ == null ? com.fc.common.socket.msg.KeepAliveMsg.C2S.getDefaultInstance() : c2S_;
        } else {
          return c2SBuilder_.getMessage();
        }
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public Builder setC2S(com.fc.common.socket.msg.KeepAliveMsg.C2S value) {
        if (c2SBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          c2S_ = value;
          onChanged();
        } else {
          c2SBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public Builder setC2S(
          com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder builderForValue) {
        if (c2SBuilder_ == null) {
          c2S_ = builderForValue.build();
          onChanged();
        } else {
          c2SBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public Builder mergeC2S(com.fc.common.socket.msg.KeepAliveMsg.C2S value) {
        if (c2SBuilder_ == null) {
          if (c2S_ != null) {
            c2S_ =
              com.fc.common.socket.msg.KeepAliveMsg.C2S.newBuilder(c2S_).mergeFrom(value).buildPartial();
          } else {
            c2S_ = value;
          }
          onChanged();
        } else {
          c2SBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public Builder clearC2S() {
        if (c2SBuilder_ == null) {
          c2S_ = null;
          onChanged();
        } else {
          c2S_ = null;
          c2SBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder getC2SBuilder() {
        
        onChanged();
        return getC2SFieldBuilder().getBuilder();
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder getC2SOrBuilder() {
        if (c2SBuilder_ != null) {
          return c2SBuilder_.getMessageOrBuilder();
        } else {
          return c2S_ == null ?
              com.fc.common.socket.msg.KeepAliveMsg.C2S.getDefaultInstance() : c2S_;
        }
      }
      /**
       * <code>.tutorial.C2S c2s = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fc.common.socket.msg.KeepAliveMsg.C2S, com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder, com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder> 
          getC2SFieldBuilder() {
        if (c2SBuilder_ == null) {
          c2SBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fc.common.socket.msg.KeepAliveMsg.C2S, com.fc.common.socket.msg.KeepAliveMsg.C2S.Builder, com.fc.common.socket.msg.KeepAliveMsg.C2SOrBuilder>(
                  getC2S(),
                  getParentForChildren(),
                  isClean());
          c2S_ = null;
        }
        return c2SBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.C2SMsg)
    }

    // @@protoc_insertion_point(class_scope:tutorial.C2SMsg)
    private static final com.fc.common.socket.msg.KeepAliveMsg.C2SMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fc.common.socket.msg.KeepAliveMsg.C2SMsg();
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.C2SMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2SMsg>
        PARSER = new com.google.protobuf.AbstractParser<C2SMsg>() {
      @java.lang.Override
      public C2SMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2SMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2SMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fc.common.socket.msg.KeepAliveMsg.C2SMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2CMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.S2CMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    boolean hasS2C();
    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    com.fc.common.socket.msg.KeepAliveMsg.S2C getS2C();
    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.S2CMsg}
   */
  public  static final class S2CMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.S2CMsg)
      S2CMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2CMsg.newBuilder() to construct.
    private S2CMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2CMsg() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2CMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2CMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder subBuilder = null;
              if (s2C_ != null) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.fc.common.socket.msg.KeepAliveMsg.S2C.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2CMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2CMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.class, com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_FIELD_NUMBER = 3;
    private com.fc.common.socket.msg.KeepAliveMsg.S2C s2C_;
    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    public boolean hasS2C() {
      return s2C_ != null;
    }
    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    public com.fc.common.socket.msg.KeepAliveMsg.S2C getS2C() {
      return s2C_ == null ? com.fc.common.socket.msg.KeepAliveMsg.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>.tutorial.S2C s2c = 3;</code>
     */
    public com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder getS2COrBuilder() {
      return getS2C();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (s2C_ != null) {
        output.writeMessage(3, getS2C());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (s2C_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fc.common.socket.msg.KeepAliveMsg.S2CMsg)) {
        return super.equals(obj);
      }
      com.fc.common.socket.msg.KeepAliveMsg.S2CMsg other = (com.fc.common.socket.msg.KeepAliveMsg.S2CMsg) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (hasS2C() != other.hasS2C()) return false;
      if (hasS2C()) {
        if (!getS2C()
            .equals(other.getS2C())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fc.common.socket.msg.KeepAliveMsg.S2CMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.S2CMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.S2CMsg)
        com.fc.common.socket.msg.KeepAliveMsg.S2CMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2CMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2CMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.class, com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.Builder.class);
      }

      // Construct using com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2C_ = null;
          s2CBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.internal_static_tutorial_S2CMsg_descriptor;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2CMsg getDefaultInstanceForType() {
        return com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2CMsg build() {
        com.fc.common.socket.msg.KeepAliveMsg.S2CMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fc.common.socket.msg.KeepAliveMsg.S2CMsg buildPartial() {
        com.fc.common.socket.msg.KeepAliveMsg.S2CMsg result = new com.fc.common.socket.msg.KeepAliveMsg.S2CMsg(this);
        result.code_ = code_;
        result.msg_ = msg_;
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fc.common.socket.msg.KeepAliveMsg.S2CMsg) {
          return mergeFrom((com.fc.common.socket.msg.KeepAliveMsg.S2CMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fc.common.socket.msg.KeepAliveMsg.S2CMsg other) {
        if (other == com.fc.common.socket.msg.KeepAliveMsg.S2CMsg.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fc.common.socket.msg.KeepAliveMsg.S2CMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fc.common.socket.msg.KeepAliveMsg.S2CMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.fc.common.socket.msg.KeepAliveMsg.S2C s2C_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fc.common.socket.msg.KeepAliveMsg.S2C, com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder, com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder> s2CBuilder_;
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public boolean hasS2C() {
        return s2CBuilder_ != null || s2C_ != null;
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? com.fc.common.socket.msg.KeepAliveMsg.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public Builder setS2C(com.fc.common.socket.msg.KeepAliveMsg.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public Builder setS2C(
          com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public Builder mergeS2C(com.fc.common.socket.msg.KeepAliveMsg.S2C value) {
        if (s2CBuilder_ == null) {
          if (s2C_ != null) {
            s2C_ =
              com.fc.common.socket.msg.KeepAliveMsg.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2C_ = null;
          s2CBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder getS2CBuilder() {
        
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      public com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              com.fc.common.socket.msg.KeepAliveMsg.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>.tutorial.S2C s2c = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fc.common.socket.msg.KeepAliveMsg.S2C, com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder, com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fc.common.socket.msg.KeepAliveMsg.S2C, com.fc.common.socket.msg.KeepAliveMsg.S2C.Builder, com.fc.common.socket.msg.KeepAliveMsg.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.S2CMsg)
    }

    // @@protoc_insertion_point(class_scope:tutorial.S2CMsg)
    private static final com.fc.common.socket.msg.KeepAliveMsg.S2CMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fc.common.socket.msg.KeepAliveMsg.S2CMsg();
    }

    public static com.fc.common.socket.msg.KeepAliveMsg.S2CMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2CMsg>
        PARSER = new com.google.protobuf.AbstractParser<S2CMsg>() {
      @java.lang.Override
      public S2CMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2CMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2CMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fc.common.socket.msg.KeepAliveMsg.S2CMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_C2S_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_C2S_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_C2SMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_C2SMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_S2CMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_S2CMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022KeepAliveMsg.proto\022\010tutorial\"\030\n\003C2S\022\021\n" +
      "\ttimestamp\030\001 \001(\003\"\030\n\003S2C\022\021\n\ttimestamp\030\001 \001" +
      "(\003\"$\n\006C2SMsg\022\032\n\003c2s\030\001 \001(\0132\r.tutorial.C2S" +
      "\"?\n\006S2CMsg\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\032\n" +
      "\003s2c\030\003 \001(\0132\r.tutorial.S2CB*\n\030com.fc.comm" +
      "on.socket.msgB\014KeepAliveMsgH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_C2S_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_C2S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_C2S_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_tutorial_S2C_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_S2C_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_tutorial_C2SMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_C2SMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_C2SMsg_descriptor,
        new java.lang.String[] { "C2S", });
    internal_static_tutorial_S2CMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tutorial_S2CMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_S2CMsg_descriptor,
        new java.lang.String[] { "Code", "Msg", "S2C", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
