// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoID.proto

package com.fc.common.socket.msg;

public final class ProtoID {
  private ProtoID() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息头
   * </pre>
   *
   * Protobuf enum {@code tutorial.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEF = 0;</code>
     */
    DEF(0),
    /**
     * <pre>
     *注册
     * </pre>
     *
     * <code>MSG_REG = 1;</code>
     */
    MSG_REG(1),
    /**
     * <pre>
     *注册返回
     * </pre>
     *
     * <code>MSG_REG_PUSH = 11;</code>
     */
    MSG_REG_PUSH(11),
    /**
     * <code>PING = 1001;</code>
     */
    PING(1001),
    /**
     * <code>PONG = 1901;</code>
     */
    PONG(1901),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEF = 0;</code>
     */
    public static final int DEF_VALUE = 0;
    /**
     * <pre>
     *注册
     * </pre>
     *
     * <code>MSG_REG = 1;</code>
     */
    public static final int MSG_REG_VALUE = 1;
    /**
     * <pre>
     *注册返回
     * </pre>
     *
     * <code>MSG_REG_PUSH = 11;</code>
     */
    public static final int MSG_REG_PUSH_VALUE = 11;
    /**
     * <code>PING = 1001;</code>
     */
    public static final int PING_VALUE = 1001;
    /**
     * <code>PONG = 1901;</code>
     */
    public static final int PONG_VALUE = 1901;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return DEF;
        case 1: return MSG_REG;
        case 11: return MSG_REG_PUSH;
        case 1001: return PING;
        case 1901: return PONG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fc.common.socket.msg.ProtoID.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.MsgType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProtoID.proto\022\010tutorial*G\n\007MsgType\022\007\n\003" +
      "DEF\020\000\022\013\n\007MSG_REG\020\001\022\020\n\014MSG_REG_PUSH\020\013\022\t\n\004" +
      "PING\020\351\007\022\t\n\004PONG\020\355\016B%\n\030com.fc.common.sock" +
      "et.msgB\007ProtoIDH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
