
spring:
  profiles: dev


      
logging:
  config: classpath:log4j2-dev.yml


netty-websocket:
  protocol: ws
  host: localhost
  port: 9902
  path: /hall

socks5:
  port: 8877
  isAuth: true
  username: test123
  password: pwd789
