
spring:
  profiles: dev


      
logging:
  config: classpath:log4j2-dev.yml


netty-websocket:
  protocol: ws
  host: localhost
  port: 9902
  path: /hall


#curl -v -x socks5://test123:pwd789@127.0.0.1:8877 https://devsdkapi.fanfq.com/sdk/api/req/analysis
socks5:
  port: 8877
  isAuth: true
  username: test123
  password: pwd789
